v2CommonCrossLogin="v2/Common/CrossLogin"
# GetPowerStationPowerAndIncomeByDay = "v2/PowerStationMonitor/GetPowerStationPowerAndIncomeByDay"
# GetPowerStationPacByDayForApp = "PowerStationMonitor/GetPowerStationPacByDayForApp"
GetPowerStationMonitorDetail = "PowerStationMonitor/GetPowerStationMonitorDetail"
GetGetPowerStationStatus = "PowerStationMonitor/GetPowerStationStatus"
GetStatPowerStationKPI = "PowerStationMonitor/StatPowerStationKPI"
GetQueryPowerStationMonitor = "PowerStationMonitor/QueryPowerStationMonitor"

PowerStation_GetPowerStationTips = "PowerStation/GetPowerStationTips"
PowerStationGetUserInfoByPowerStation = 'PowerStation/GetUserInfoByPowerStation'

StatGetPowerStationAndPowerTotal = "Stat/GetPowerStationAndPowerTotal"


HistoryDataQueryPowerStationByHistory = "HistoryData/QueryPowerStationByHistory"
HistoryDataQueryPowerStationByHistoryForDaily = "HistoryData/QueryPowerStationByHistoryForDaily"


PowerStationV1GetPowerCharts= "v1/PowerStation/GetPowerCharts"
PowerStationV1GetEnergeStatisticsCharts= "v1/PowerStation/GetEnergeStatisticsCharts"

ReportDataV1GetPowerStationPowerReportDetialByMonth = "v1/ReportData/GetPowerStationPowerReportDetialByMonth"