v2CommonCrossLogin="v2/Common/CrossLogin"
GetPowerStationPowerAndIncomeByDay = "v2/PowerStationMonitor/GetPowerStationPowerAndIncomeByDay"
GetPowerStationPacByDayForApp = "PowerStationMonitor/GetPowerStationPacByDayForApp"